#include <allegro.h>
#include <time.h>
#include "header.h"

void ModeSpeedrun(t_ninja*ninja)
{
    ///LES INITIALISATION CHARGEMENT FICHIER SAUVEGARDE

    ///DEMANDE NON DU JOUEUR POUR LA FUTUR SAUVEGARDE

    ///LANCEMENT DU TIMER

    ///LANCEMENT NIV1

    ///LANCEMENT NIV2

    ///LANCEMENT NIV3

    ///SI PERSONNAGE MEURT PROPOSER DE RECOMMENCER (SOUS PROGRAMMES RECURSIF)
    ///SINON PROPOSER DE QUITTER OU DE REVENIR AU MENU

    ///FIN DU TIMER AFFICHAGE DU TEMPS DU JOUEUERS PLUS SAUVEGARDE DE SON RECORD

}
